export type Overview = {
  latestTradeDate: string;
  latestRunAt: string;
  latestMode: string;
  scanRuns: number;
  signals: number;
  candidateEvents: number;
  candidateOutcomes: number;
  candidateMatureT3: number;
  candidateRejectedMatureT3: number;
  featureSnapshots: number;
  predictions: number;
  prospectivePredictions: number;
  predictionOutcomes: number;
  maturePredictionOutcomes: number;
  modelVersions: number;
  newsEvidence: number;
  backtestResults: number;
  formalSelections: number;
  formalBacktestResults: number;
  formalMatureT3: number;
  formalCompleteT20: number;
  matureT3: number;
  completeT20: number;
  paperAccounts: number;
  paperClosedTrades: number;
  paperProspectiveClosedTrades: number;
};

export type ResearchQuality = {
  executionVersion: string;
  outcomeCoveragePct: number;
  matureCandidateOutcomes: number;
  matureRejectedOutcomes: number;
  matureSelectedOutcomes: number;
  uniqueTradeDates: number;
  meanNetReturn3d: number | null;
  meanExcessReturn3d: number | null;
  positiveRate3d: number | null;
  successRateT3: number | null;
  formalMeanNetReturn3d: number | null;
  formalMeanExcessReturn3d: number | null;
  rejectedMeanNetReturn3d: number | null;
  rejectedMeanExcessReturn3d: number | null;
  selectionNetLift3d: number | null;
  selectionExcessLift3d: number | null;
};

export type ResearchExperiment = {
  experimentKey: string;
  name: string;
  hypothesis: string;
  strategyFamily: string;
  executionVersion: string;
  status: string;
  evaluatedAt: string | null;
  sampleStart: string | null;
  sampleEnd: string | null;
  tradeDates: number | null;
  trades: number | null;
  folds: number | null;
  meanNetReturn: number | null;
  meanExcessReturn: number | null;
  positiveRate: number | null;
  annualizedSharpe: number | null;
  probabilisticSharpe: number | null;
  maxDrawdown: number | null;
  profitableFoldRate: number | null;
  decisionDates: number | null;
  participationRatePct: number | null;
  meanDailyNetReturn: number | null;
  meanDailyExcessReturn: number | null;
  rankingTarget: "net" | "excess" | "peer_rank" | null;
  predictionQuantile: number | null;
  predictionThreshold: number | null;
  evaluationScope: string | null;
  holdoutEvaluated: boolean | null;
  formalRankingEnabled: boolean | null;
  institutionalNetLift: number | null;
  institutionalExcessLift: number | null;
  institutionalCondition: string | null;
  modelVersion: string | null;
  qualified: boolean;
  rejectionReasons: string[];
};

export type LearnabilityPortfolio = {
  trades: number;
  decisionDates: number;
  participatingDates: number;
  participationRatePct: number | null;
  meanDailyNetReturn: number | null;
  meanDailyExcessReturn: number | null;
  positiveDayRate: number | null;
  maxDrawdown: number | null;
  profitableFoldRate: number | null;
};

export type LearnabilityAuditRow = {
  key: string;
  entryMethod: string;
  holdingHorizon: number;
  diagnosis: string;
  predictionThreshold: number | null;
  pool: LearnabilityPortfolio & {
    filledCandidates: number;
    fillRatePct: number | null;
    positiveCandidateRate: number | null;
    profitableTopKCapacityRatePct: number | null;
  };
  oracle: LearnabilityPortfolio;
  formalRule: LearnabilityPortfolio;
  model: LearnabilityPortfolio & {
    selectedFillRatePct: number | null;
    oracleOverlapRatePct: number | null;
    opportunityCapturePct: number | null;
    oracleHeadroom: number | null;
  };
  rankability: {
    icDates: number;
    meanRankIc: number | null;
    rankIcCi95Low: number | null;
    rankIcCi95High: number | null;
    positiveRankIcRate: number | null;
    topBottomNetSpread: number | null;
    topBottomExcessSpread: number | null;
    topBottomDates: number;
  };
};

export type CandidateLearnabilityAudit = {
  auditVersion: string;
  evaluatedAt: string | null;
  evaluationScope: string;
  trainingStart: string | null;
  trainingEnd: string | null;
  validationStart: string | null;
  validationEnd: string | null;
  holdoutEvaluated: boolean;
  formalRankingEnabled: boolean;
  reservedHoldoutTradeDates: number;
  primarySpecKey: string | null;
  primaryDiagnosis: string;
  bestDiagnosticSpecKey: string | null;
  primary: LearnabilityAuditRow | null;
  rows: LearnabilityAuditRow[];
};

export type ResearchIntegrityCheck = {
  key: string;
  label: string;
  passed: boolean;
  detail: string;
  requirement: string;
};

export type ResearchIntegrityGate = {
  version: string;
  status: "blocked" | "review_required" | "approved";
  recommendationMode: "research_only" | "formal";
  evidenceReady: boolean;
  manualApproval: boolean;
  formalRecommendationsAllowed: boolean;
  passedChecks: number;
  totalChecks: number;
  checks: ResearchIntegrityCheck[];
};

export type ResearchHealth = {
  status: "healthy" | "building" | "warning" | "critical";
  checkedAt: string;
  latestTradeDate: string;
  prospectiveCohorts: number;
  pendingCohorts: number;
  matureT3Cohorts: number;
  expectedMatureT3: number;
  staleOutcomes: number;
  oldestPendingSessions: number;
  maturityCoveragePct: number;
  executionScenarioCandidates: number;
  executionScenarios: number;
  executionScenariosMatureT20: number;
  executionScenariosPending: number;
  replayRuns: number;
  completedReplayRuns: number;
  latestReplayAt: string | null;
  latestReplayStatus: string | null;
  latestReplayStart: string | null;
  latestReplayEnd: string | null;
  replayEvents: number;
  replaySelected: number;
  replayMatureT3: number;
  replayAvailableSymbols: number;
  replayTradingDays: number;
  replayUniverseSnapshots: number;
  replayUniverseQualityStatus: "verified" | "partial" | "unverified";
  replayUniversePartialMemberships: number;
  replayUniverseMembershipIntervals: number;
  replayCheckpointTotal: number;
  replayCheckpointCompleted: number;
  replayAttributionRows: number;
  replayAttributionDimensions: number;
  replayAttributionAt: string | null;
  replayEvidenceStorageMode: "none" | "raw" | "summary_only";
  replayRawEventsPersisted: number;
  warnings: string[];
  replayDataWarnings: string[];
  replaySelectedMeanNetReturn3d: number | null;
  replaySelectedMeanExcessReturn3d: number | null;
  replayRejectedMeanNetReturn3d: number | null;
  replayRejectedMeanExcessReturn3d: number | null;
  replaySelectionNetLift3d: number | null;
  replaySelectionExcessLift3d: number | null;
  replaySelectedSuccessRateT3: number | null;
  replayRejectedSuccessRateT3: number | null;
  formalMatureCandidates: number;
  formalMatureSelected: number;
  formalMatureRejected: number;
  formalSelectedTradeDates: number;
  formalSelectedMeanNetReturn3d: number | null;
  formalSelectedMeanExcessReturn3d: number | null;
  formalRejectedMeanNetReturn3d: number | null;
  formalRejectedMeanExcessReturn3d: number | null;
  formalSelectionNetLift3d: number | null;
  formalSelectionExcessLift3d: number | null;
  strategyChallengerEvaluatedAt: string | null;
  strategyChallengerVersion: string | null;
  strategyChallengerStatus: "not_evaluated" | "blocked" | "prospective_shadow_ready";
  strategyChallengerSelectedKey: string | null;
  strategyRecommendationMode: "cash" | "shadow";
  strategyQualifiedCandidates: number;
  strategyCandidateCount: number;
  integrityGate: ResearchIntegrityGate;
};

export type CloudEvidence = {
  backend: "supabase_storage";
  schemaVersion: string;
  migrationMode: "dual_write" | "cloud_primary";
  gitDatabaseFallback: boolean;
  configured: boolean;
  status: "unconfigured" | "verified" | "failed";
  operation: "" | "push" | "restore" | "prune";
  eventAt: string;
  snapshotKey: string;
  objectPath: string;
  databaseSha256: string;
  databaseBytes: number;
  compressedBytes: number;
  latestScanRunId: number | null;
  latestTradeDate: string;
  sourceWorkflow: string;
  auditVersion: string;
  auditStatus: "not_run" | "ready" | "blocked";
  auditAt: string;
  cutoverReady: boolean;
  passedChecks: number;
  totalChecks: number;
  dailySnapshots: number;
  verifiedPushes: number;
  workflowCount: number;
  cutoverChecks: Array<{
    key: string;
    label: string;
    passed: boolean;
    detail: string;
    requirement: string;
  }>;
  message: string;
};

export type ReplayAttributionRow = {
  dimension: string;
  dimensionLabel: string;
  bucketKey: string;
  bucketLabel: string;
  sortOrder: number;
  selectionScope: "all" | "selected" | "rejected";
  selectionLabel: string;
  sampleCount: number;
  selectedCount: number;
  matureT1: number;
  matureT3: number;
  matureT5: number;
  meanNetReturn1d: number | null;
  meanNetReturn3d: number | null;
  meanNetReturn5d: number | null;
  meanExcessReturn3d: number | null;
  positiveRate3d: number | null;
  successRateT3: number | null;
  meanMaxDrawdown3d: number | null;
  standardError3d: number | null;
  ci95Low3d: number | null;
  ci95High3d: number | null;
};

export type ReplayAttribution = {
  replayRunId: number | null;
  attributionVersion: string;
  generatedAt: string;
  dimensions: Array<{ key: string; label: string }>;
  rows: ReplayAttributionRow[];
};

export type Candidate = {
  tradeDate: string;
  runAt: string;
  selectionRank: number | null;
  rawRank: number;
  code: string;
  name: string;
  industry: string;
  strategies: string[];
  score: number;
  signalPrice: number;
  pctChange: number;
  turnoverBillion: number;
  volumeRatio5: number;
  intradayPosition: number | null;
  observationPrice: number | null;
  chaseLimit: number | null;
  stopDistancePct: number | null;
  tradable: boolean;
  isSelected: boolean;
  selectionStatus: string;
  statusLabel: string;
  riskFlags: string[];
  blockReasons: string[];
  policyVersion: string;
  aiModelVersion: string | null;
  aiProspective: boolean | null;
  aiRank: number | null;
  aiShadowSelected: boolean | null;
  aiScore: number | null;
  aiProbabilityT3: number | null;
  aiExpectedExcess3d: number | null;
  aiExpectedDrawdown3d: number | null;
  aiAction: string | null;
  aiNewsSentiment: string | null;
  aiNewsConfidence: number | null;
  aiNewsEvidenceCount: number;
  aiNewsSummary: string;
};

export type DailyCandidate = {
  tradeDate: string;
  candidates: number;
  tradable: number;
  selected: number;
  analyzedRuns: number;
};

export type Performance = {
  tradeDate: string;
  mode: string;
  strategy: string;
  strategyLabel: string;
  code: string;
  name: string;
  maturedHorizon: number;
  outcomeStatus: string;
  netReturn1d: number | null;
  netReturn3d: number | null;
  netReturn5d: number | null;
  excessReturn3d: number | null;
  maxReturn3d: number | null;
  maxDrawdown3d: number | null;
  successT3: boolean | null;
  costsBps: number;
  entryMethod: string;
  testedAt: string;
  isFormalSelection: boolean;
  policyVersion: string;
};

export type ScanRun = {
  id: number;
  runAt: string;
  tradeDate: string;
  mode: string;
  source: string;
  strategyVersion: string;
  gitCommit: string;
  reportPath: string;
  automationSlot: string;
};

export type BacktestRun = {
  id: number;
  startedAt: string;
  finishedAt: string | null;
  status: string;
  signalsRequested: number;
  completedCount: number;
  partialCount: number;
  skippedCount: number;
  errorText: string | null;
  selectionScope: string;
};

export type AiModel = {
  modelName: string;
  version: string;
  status: string;
  featureVersion: string;
  trainingStart: string;
  trainingEnd: string;
  createdAt: string;
  metrics: {
    samples?: number;
    positive_samples?: number;
    training_samples?: number;
    validation_samples?: number;
    validation_auc?: number | null;
    validation_brier?: number;
    validation_excess_mae?: number;
    validation_drawdown_mae?: number;
    validation_start?: string;
    validation_end?: string;
    unique_trade_dates?: number;
    embargo_trade_dates?: string[];
    outcome_source?: string;
    walk_forward_folds?: number;
    oof_trade_dates?: number;
  };
};

export type ModelChallenger = {
  modelVersion: string;
  evaluatedAt: string;
  status: string;
  oofTradeDates: number;
  oofCandidates: number;
  challengerTrades: number;
  championTrades: number;
  challengerMeanNetReturn: number | null;
  challengerMeanExcessReturn: number | null;
  championMeanNetReturn: number | null;
  championMeanExcessReturn: number | null;
  netReturnLift: number | null;
  excessReturnLift: number | null;
  challengerMaxDrawdown: number | null;
  profitableFoldRate: number | null;
  qualified: boolean;
  rejectionReasons: string[];
};

export type StrategyChallengerCandidate = {
  experimentKey: string;
  name: string;
  qualified: boolean;
  rejectionReasons: string[];
  entryMethod: string;
  holdingHorizon: number;
  rankingTarget: string;
  trades: number;
  decisionDates: number;
  participationRatePct: number | null;
  meanDailyNetReturn: number | null;
  meanDailyExcessReturn: number | null;
  formalBaselineMeanDailyNetReturn: number | null;
  formalBaselineMeanDailyExcessReturn: number | null;
  formalNetLift: number | null;
  formalExcessLift: number | null;
  annualizedSharpe: number | null;
  probabilisticSharpe: number | null;
  maxDrawdown: number | null;
  profitableFoldRate: number | null;
  walkForwardFolds: number;
  sampleStart: string | null;
  sampleEnd: string | null;
  reservedHoldoutStart: string | null;
  reservedHoldoutEnd: string | null;
  reservedHoldoutTradeDates: number;
  holdoutEvaluated: boolean;
};

export type StrategyExecutionPhase = {
  decisionDates: number;
  participatingDates: number;
  participationRatePct: number;
  trades: number;
  meanNetReturn: number | null;
  meanExcessReturn: number | null;
  meanDailyNetReturn: number;
  meanDailyExcessReturn: number;
  positiveDayRate: number;
};

export type StrategyExecutionRow = {
  key: string;
  entryMethod: string;
  holdingHorizon: number;
  development: StrategyExecutionPhase;
  validation: StrategyExecutionPhase;
  holdoutAudit: StrategyExecutionPhase;
};

export type StrategyChallengerSnapshot = {
  version: string;
  evaluatedAt: string | null;
  status: "not_evaluated" | "blocked" | "prospective_shadow_ready";
  recommendationMode: "cash" | "shadow";
  selectedExperimentKey: string | null;
  diagnosticLeaderKey: string | null;
  qualifiedCandidates: number;
  candidateCount: number;
  datasetFingerprint: string;
  datasetRows: number;
  datasetStart: string | null;
  datasetEnd: string | null;
  lockedComparisons: number;
  multipleTestingPsrGate: number | null;
  selectionUsesHoldout: boolean;
  formalRankingEnabled: boolean;
  candidateLeaderboard: StrategyChallengerCandidate[];
  executionMatrix: StrategyExecutionRow[];
};

export type PaperAccount = {
  accountKey: string;
  name: string;
  strategyKind: "rule" | "ai" | "ai_capital";
  evidenceMode: string;
  policyVersion: string;
  executionVersion: string;
  startingCash: number;
  cash: number;
  equity: number;
  totalReturnPct: number;
  maxDrawdownPct: number;
  closedTrades: number;
  winningTrades: number;
  winRate: number | null;
  openPositions: number;
  pendingOrders: number;
  skippedOrders: number;
  firstSignalAt: string | null;
  lastEquityAt: string | null;
  comparisonStartAt: string | null;
  comparisonReturnPct: number | null;
  status: string;
  updatedAt: string;
  avgReturnPct: number | null;
  grossProfit: number;
  grossLoss: number;
  profitFactor: number | null;
  signalDates: number;
  avgExcessReturnPct: number | null;
  avgAllocationWeight: number | null;
  config: {
    starting_cash?: number;
    max_positions?: number;
    position_size_pct?: number;
    risk_budget_pct?: number;
    cash_buffer_pct?: number;
    min_trade_value?: number;
    costs_bps?: number;
    max_industry_exposure_pct?: number | null;
    capital_policy?: {
      account_key: string;
      role: "benchmark" | "challenger" | "legacy";
      evidence_start_date: string | null;
      max_daily_selections: number | null;
      max_per_industry: number | null;
      weighting: "equal" | "score_proportional";
      daily_budget_pct: number | null;
      tournament_version: string | null;
    };
  };
};

export type CapitalTournament = {
  version: string;
  evidenceStartDate: string;
  evidenceDays: number;
  minimumEvidenceDays: number;
  minimumClosedTrades: number;
  benchmarkAccountKey: string | null;
  provisionalLeaderAccountKey: string | null;
  reviewCandidateAccountKey: string | null;
  status: "collecting_evidence" | "manual_review_required";
  automaticPromotion: false;
  accounts: Array<{
    accountKey: string;
    name: string;
    role: "benchmark" | "challenger";
    policy: NonNullable<PaperAccount["config"]["capital_policy"]>;
    closedTrades: number;
    signalDates: number;
    totalReturnPct: number;
    avgExcessReturnPct: number | null;
    maxDrawdownPct: number;
    returnLiftVsTop3Pct: number | null;
    riskAdjustedScore: number | null;
    riskAdjustedLiftVsTop3: number | null;
    qualifiedForReview: boolean;
    rejectionReasons: string[];
  }>;
};

export type PaperEquityPoint = {
  accountKey: string;
  asOf: string;
  cash: number;
  marketValue: number;
  equity: number;
  totalReturnPct: number;
  drawdownPct: number;
  openPositions: number;
  closedTrades: number;
};

export type PaperTrade = {
  accountKey: string;
  sourceType: string;
  sourceId: number;
  signalDate: string;
  signalAt: string;
  code: string;
  name: string;
  industry: string;
  rankOrder: number | null;
  modelVersion: string | null;
  finalScore: number | null;
  allocationWeight: number | null;
  benchmarkReturnPct: number | null;
  excessReturnPct: number | null;
  entryAt: string | null;
  entryPrice: number | null;
  quantity: number | null;
  investedAmount: number | null;
  chaseLimit: number | null;
  stopPrice: number | null;
  exitAt: string | null;
  exitPrice: number | null;
  exitReason: string | null;
  netReturnPct: number | null;
  realizedPnl: number | null;
  markAt: string | null;
  markPrice: number | null;
  marketValue: number | null;
  unrealizedPnl: number | null;
  maxReturnPct: number | null;
  maxDrawdownPct: number | null;
  status: "pending" | "open" | "closed" | "skipped";
  skipReason: string | null;
};

export type GlobalMarketInstrument = {
  key: string;
  symbol: string | null;
  name: string;
  group: string;
  region: string;
  assetClass: string;
  currency: string;
  marketAt: string | null;
  price: number | null;
  previousClose: number | null;
  pctChange: number | null;
  return5d: number | null;
  shockZ: number | null;
  volume: number | null;
  sourceName: string;
  sourceTier: string;
  dataStatus: "fresh" | "delayed" | "closed" | "stale" | "unavailable" | "not_connected";
  sessionStatus: "open" | "closed";
  latencyMinutes: number | null;
  impactDirection: number;
  modelWeight: number;
  impactPoints: number;
};

export type GlobalMarketSnapshot = {
  modelVersion: string;
  snapshotAt: string;
  score: number;
  regimeLabel: string;
  taiwanBiasScore: number;
  taiwanBiasLabel: string;
  components: Array<{
    key: string;
    name: string;
    score: number;
    coverage: number;
    total: number;
  }>;
  drivers: Array<{
    key: string;
    name: string;
    impactPoints: number;
    pctChange: number | null;
    tone: "positive" | "negative";
    reason: string;
  }>;
  instruments: GlobalMarketInstrument[];
  history: Array<{
    snapshotAt: string;
    score: number;
    taiwanBiasScore: number;
    coveragePct: number;
    activeFreshPct: number;
  }>;
  quality: {
    status: string;
    coveragePct: number;
    activeFreshPct: number;
    available: number;
    total: number;
    missingKeys: string[];
    warnings: string[];
    formalRankingEnabled: boolean;
  };
};

export type InstitutionalFlowSnapshot = {
  featureVersion: string;
  researchGeneration: string;
  latestTradeDate: string;
  fetchedAt: string;
  rawRows: number;
  symbols: number;
  candidateTargets: number;
  featureSnapshots: number;
  completeFeatures: number;
  coveragePct: number;
  completeCoveragePct: number;
  sources: Array<{
    market: string;
    status: string;
    reportDate: string | null;
    rowCount: number;
    sourceName: string;
    sourceUrl: string;
    fetchedAt: string;
    errorText: string | null;
  }>;
  candidates: Array<{
    code: string;
    name: string;
    industry: string;
    score: number | null;
    sourceTradeDate: string | null;
    observations20d: number | null;
    coverageStatus: string | null;
    foreignNetZ20: number | null;
    trustNetZ20: number | null;
    totalNetZ20: number | null;
    foreignStreakDays: number | null;
    trustStreakDays: number | null;
    totalStreakDays: number | null;
    agreementScore1d: number | null;
  }>;
  quality: {
    status: string;
    formalRankingEnabled: boolean;
    historicalUse: string;
    promotionGate: string;
    warnings: string[];
  };
};

export type DashboardSnapshot = {
  schemaVersion: string;
  generatedAt: string;
  candidateDetailDays: number;
  overview: Overview;
  researchQuality: ResearchQuality;
  researchHealth: ResearchHealth;
  replayAttribution: ReplayAttribution;
  researchExperiments: ResearchExperiment[];
  learnabilityAudit: CandidateLearnabilityAudit;
  candidates: Candidate[];
  dailyCandidates: DailyCandidate[];
  statusCounts: { status: string; count: number; label: string }[];
  performance: Performance[];
  scanRuns: ScanRun[];
  backtestRuns: BacktestRun[];
  aiModels: AiModel[];
  modelChallengers: ModelChallenger[];
  strategyChallenger: StrategyChallengerSnapshot;
  paperAccounts: PaperAccount[];
  paperEquity: PaperEquityPoint[];
  paperTrades: PaperTrade[];
  capitalTournament: CapitalTournament;
  globalMarket: GlobalMarketSnapshot;
  institutionalFlow: InstitutionalFlowSnapshot;
  cloudEvidence: CloudEvidence;
};

export type WorkflowRun = {
  id: number;
  name: string;
  displayTitle: string;
  event: string;
  status: string;
  conclusion: string | null;
  createdAt: string;
  updatedAt: string;
  url: string;
};
