export type Overview = {
  latestTradeDate: string;
  latestRunAt: string;
  latestMode: string;
  scanRuns: number;
  signals: number;
  candidateEvents: number;
  candidateOutcomes: number;
  candidateMatureT3: number;
  candidateRejectedMatureT3: number;
  featureSnapshots: number;
  predictions: number;
  prospectivePredictions: number;
  predictionOutcomes: number;
  maturePredictionOutcomes: number;
  modelVersions: number;
  newsEvidence: number;
  backtestResults: number;
  formalSelections: number;
  formalBacktestResults: number;
  formalMatureT3: number;
  formalCompleteT20: number;
  matureT3: number;
  completeT20: number;
  paperAccounts: number;
  paperClosedTrades: number;
  paperProspectiveClosedTrades: number;
};

export type ResearchQuality = {
  executionVersion: string;
  outcomeCoveragePct: number;
  matureCandidateOutcomes: number;
  matureRejectedOutcomes: number;
  matureSelectedOutcomes: number;
  uniqueTradeDates: number;
  meanNetReturn3d: number | null;
  meanExcessReturn3d: number | null;
  positiveRate3d: number | null;
  successRateT3: number | null;
  formalMeanNetReturn3d: number | null;
  formalMeanExcessReturn3d: number | null;
  rejectedMeanNetReturn3d: number | null;
  rejectedMeanExcessReturn3d: number | null;
  selectionNetLift3d: number | null;
  selectionExcessLift3d: number | null;
};

export type ResearchExperiment = {
  experimentKey: string;
  name: string;
  hypothesis: string;
  strategyFamily: string;
  executionVersion: string;
  status: string;
  evaluatedAt: string | null;
  sampleStart: string | null;
  sampleEnd: string | null;
  tradeDates: number | null;
  trades: number | null;
  folds: number | null;
  meanNetReturn: number | null;
  meanExcessReturn: number | null;
  positiveRate: number | null;
  annualizedSharpe: number | null;
  probabilisticSharpe: number | null;
  maxDrawdown: number | null;
  profitableFoldRate: number | null;
  qualified: boolean;
  rejectionReasons: string[];
};

export type ResearchHealth = {
  status: "healthy" | "building" | "warning" | "critical";
  checkedAt: string;
  latestTradeDate: string;
  prospectiveCohorts: number;
  pendingCohorts: number;
  matureT3Cohorts: number;
  expectedMatureT3: number;
  staleOutcomes: number;
  oldestPendingSessions: number;
  maturityCoveragePct: number;
  replayRuns: number;
  completedReplayRuns: number;
  latestReplayAt: string | null;
  latestReplayStatus: string | null;
  latestReplayStart: string | null;
  latestReplayEnd: string | null;
  replayEvents: number;
  replaySelected: number;
  replayMatureT3: number;
  replayAvailableSymbols: number;
  replayTradingDays: number;
  warnings: string[];
  replayDataWarnings: string[];
  replaySelectedMeanNetReturn3d: number | null;
  replaySelectedMeanExcessReturn3d: number | null;
  replayRejectedMeanNetReturn3d: number | null;
  replayRejectedMeanExcessReturn3d: number | null;
  replaySelectionNetLift3d: number | null;
  replaySelectionExcessLift3d: number | null;
  replaySelectedSuccessRateT3: number | null;
  replayRejectedSuccessRateT3: number | null;
};

export type Candidate = {
  tradeDate: string;
  runAt: string;
  selectionRank: number | null;
  rawRank: number;
  code: string;
  name: string;
  industry: string;
  strategies: string[];
  score: number;
  signalPrice: number;
  pctChange: number;
  turnoverBillion: number;
  volumeRatio5: number;
  intradayPosition: number | null;
  observationPrice: number | null;
  chaseLimit: number | null;
  stopDistancePct: number | null;
  tradable: boolean;
  isSelected: boolean;
  selectionStatus: string;
  statusLabel: string;
  riskFlags: string[];
  blockReasons: string[];
  policyVersion: string;
  aiModelVersion: string | null;
  aiProspective: boolean | null;
  aiRank: number | null;
  aiShadowSelected: boolean | null;
  aiScore: number | null;
  aiProbabilityT3: number | null;
  aiExpectedExcess3d: number | null;
  aiExpectedDrawdown3d: number | null;
  aiAction: string | null;
  aiNewsSentiment: string | null;
  aiNewsConfidence: number | null;
  aiNewsEvidenceCount: number;
  aiNewsSummary: string;
};

export type DailyCandidate = {
  tradeDate: string;
  candidates: number;
  tradable: number;
  selected: number;
  analyzedRuns: number;
};

export type Performance = {
  tradeDate: string;
  mode: string;
  strategy: string;
  strategyLabel: string;
  code: string;
  name: string;
  maturedHorizon: number;
  outcomeStatus: string;
  netReturn1d: number | null;
  netReturn3d: number | null;
  netReturn5d: number | null;
  excessReturn3d: number | null;
  maxReturn3d: number | null;
  maxDrawdown3d: number | null;
  successT3: boolean | null;
  costsBps: number;
  entryMethod: string;
  testedAt: string;
  isFormalSelection: boolean;
  policyVersion: string;
};

export type ScanRun = {
  id: number;
  runAt: string;
  tradeDate: string;
  mode: string;
  source: string;
  strategyVersion: string;
  gitCommit: string;
  reportPath: string;
  automationSlot: string;
};

export type BacktestRun = {
  id: number;
  startedAt: string;
  finishedAt: string | null;
  status: string;
  signalsRequested: number;
  completedCount: number;
  partialCount: number;
  skippedCount: number;
  errorText: string | null;
  selectionScope: string;
};

export type AiModel = {
  modelName: string;
  version: string;
  status: string;
  featureVersion: string;
  trainingStart: string;
  trainingEnd: string;
  createdAt: string;
  metrics: {
    samples?: number;
    positive_samples?: number;
    training_samples?: number;
    validation_samples?: number;
    validation_auc?: number | null;
    validation_brier?: number;
    validation_excess_mae?: number;
    validation_drawdown_mae?: number;
    validation_start?: string;
    validation_end?: string;
    unique_trade_dates?: number;
    embargo_trade_dates?: string[];
    outcome_source?: string;
    walk_forward_folds?: number;
    oof_trade_dates?: number;
  };
};

export type ModelChallenger = {
  modelVersion: string;
  evaluatedAt: string;
  status: string;
  oofTradeDates: number;
  oofCandidates: number;
  challengerTrades: number;
  championTrades: number;
  challengerMeanNetReturn: number | null;
  challengerMeanExcessReturn: number | null;
  championMeanNetReturn: number | null;
  championMeanExcessReturn: number | null;
  netReturnLift: number | null;
  excessReturnLift: number | null;
  challengerMaxDrawdown: number | null;
  profitableFoldRate: number | null;
  qualified: boolean;
  rejectionReasons: string[];
};

export type PaperAccount = {
  accountKey: string;
  name: string;
  strategyKind: "rule" | "ai";
  evidenceMode: string;
  policyVersion: string;
  executionVersion: string;
  startingCash: number;
  cash: number;
  equity: number;
  totalReturnPct: number;
  maxDrawdownPct: number;
  closedTrades: number;
  winningTrades: number;
  winRate: number | null;
  openPositions: number;
  pendingOrders: number;
  skippedOrders: number;
  firstSignalAt: string | null;
  lastEquityAt: string | null;
  comparisonStartAt: string | null;
  comparisonReturnPct: number | null;
  status: string;
  updatedAt: string;
  avgReturnPct: number | null;
  grossProfit: number;
  grossLoss: number;
  profitFactor: number | null;
  config: {
    starting_cash?: number;
    max_positions?: number;
    position_size_pct?: number;
    cash_buffer_pct?: number;
    min_trade_value?: number;
    costs_bps?: number;
  };
};

export type PaperEquityPoint = {
  accountKey: string;
  asOf: string;
  cash: number;
  marketValue: number;
  equity: number;
  totalReturnPct: number;
  drawdownPct: number;
  openPositions: number;
  closedTrades: number;
};

export type PaperTrade = {
  accountKey: string;
  sourceType: string;
  sourceId: number;
  signalDate: string;
  signalAt: string;
  code: string;
  name: string;
  industry: string;
  rankOrder: number | null;
  modelVersion: string | null;
  entryAt: string | null;
  entryPrice: number | null;
  quantity: number | null;
  investedAmount: number | null;
  chaseLimit: number | null;
  stopPrice: number | null;
  exitAt: string | null;
  exitPrice: number | null;
  exitReason: string | null;
  netReturnPct: number | null;
  realizedPnl: number | null;
  markAt: string | null;
  markPrice: number | null;
  marketValue: number | null;
  unrealizedPnl: number | null;
  maxReturnPct: number | null;
  maxDrawdownPct: number | null;
  status: "pending" | "open" | "closed" | "skipped";
  skipReason: string | null;
};

export type GlobalMarketInstrument = {
  key: string;
  symbol: string | null;
  name: string;
  group: string;
  region: string;
  assetClass: string;
  currency: string;
  marketAt: string | null;
  price: number | null;
  previousClose: number | null;
  pctChange: number | null;
  return5d: number | null;
  shockZ: number | null;
  volume: number | null;
  sourceName: string;
  sourceTier: string;
  dataStatus: "fresh" | "delayed" | "closed" | "stale" | "unavailable" | "not_connected";
  sessionStatus: "open" | "closed";
  latencyMinutes: number | null;
  impactDirection: number;
  modelWeight: number;
  impactPoints: number;
};

export type GlobalMarketSnapshot = {
  modelVersion: string;
  snapshotAt: string;
  score: number;
  regimeLabel: string;
  taiwanBiasScore: number;
  taiwanBiasLabel: string;
  components: Array<{
    key: string;
    name: string;
    score: number;
    coverage: number;
    total: number;
  }>;
  drivers: Array<{
    key: string;
    name: string;
    impactPoints: number;
    pctChange: number | null;
    tone: "positive" | "negative";
    reason: string;
  }>;
  instruments: GlobalMarketInstrument[];
  history: Array<{
    snapshotAt: string;
    score: number;
    taiwanBiasScore: number;
    coveragePct: number;
    activeFreshPct: number;
  }>;
  quality: {
    status: string;
    coveragePct: number;
    activeFreshPct: number;
    available: number;
    total: number;
    missingKeys: string[];
    warnings: string[];
    formalRankingEnabled: boolean;
  };
};

export type DashboardSnapshot = {
  schemaVersion: string;
  generatedAt: string;
  candidateDetailDays: number;
  overview: Overview;
  researchQuality: ResearchQuality;
  researchHealth: ResearchHealth;
  researchExperiments: ResearchExperiment[];
  candidates: Candidate[];
  dailyCandidates: DailyCandidate[];
  statusCounts: { status: string; count: number; label: string }[];
  performance: Performance[];
  scanRuns: ScanRun[];
  backtestRuns: BacktestRun[];
  aiModels: AiModel[];
  modelChallengers: ModelChallenger[];
  paperAccounts: PaperAccount[];
  paperEquity: PaperEquityPoint[];
  paperTrades: PaperTrade[];
  globalMarket: GlobalMarketSnapshot;
};

export type WorkflowRun = {
  id: number;
  name: string;
  displayTitle: string;
  event: string;
  status: string;
  conclusion: string | null;
  createdAt: string;
  updatedAt: string;
  url: string;
};
